# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import booking_pb2 as booking__pb2


class BookingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getBooking = channel.unary_unary(
                '/Booking/getBooking',
                request_serializer=booking__pb2.userId.SerializeToString,
                response_deserializer=booking__pb2.BookingDataGet.FromString,
                )
        self.getListBookings = channel.unary_stream(
                '/Booking/getListBookings',
                request_serializer=booking__pb2.EmptyBooking.SerializeToString,
                response_deserializer=booking__pb2.BookingDataGet.FromString,
                )
        self.createBooking = channel.unary_unary(
                '/Booking/createBooking',
                request_serializer=booking__pb2.BookingDataPost.SerializeToString,
                response_deserializer=booking__pb2.BookingDataGet.FromString,
                )


class BookingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getListBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createBooking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.getBooking,
                    request_deserializer=booking__pb2.userId.FromString,
                    response_serializer=booking__pb2.BookingDataGet.SerializeToString,
            ),
            'getListBookings': grpc.unary_stream_rpc_method_handler(
                    servicer.getListBookings,
                    request_deserializer=booking__pb2.EmptyBooking.FromString,
                    response_serializer=booking__pb2.BookingDataGet.SerializeToString,
            ),
            'createBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.createBooking,
                    request_deserializer=booking__pb2.BookingDataPost.FromString,
                    response_serializer=booking__pb2.BookingDataGet.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Booking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Booking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Booking/getBooking',
            booking__pb2.userId.SerializeToString,
            booking__pb2.BookingDataGet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getListBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Booking/getListBookings',
            booking__pb2.EmptyBooking.SerializeToString,
            booking__pb2.BookingDataGet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Booking/createBooking',
            booking__pb2.BookingDataPost.SerializeToString,
            booking__pb2.BookingDataGet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
