# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x18\n\x06userId\x12\x0e\n\x06userid\x18\x01 \x01(\t\"7\n\x0e\x42ookingDataGet\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x15\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x06.dates\"@\n\x0f\x42ookingDataPost\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0f\n\x07movieid\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\"%\n\x05\x64\x61tes\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x0e\n\x0c\x45mptyBooking2\xa0\x01\n\x07\x42ooking\x12(\n\ngetBooking\x12\x07.userId\x1a\x0f.BookingDataGet\"\x00\x12\x35\n\x0fgetListBookings\x12\r.EmptyBooking\x1a\x0f.BookingDataGet\"\x00\x30\x01\x12\x34\n\rcreateBooking\x12\x10.BookingDataPost\x1a\x0f.BookingDataGet\"\x00\x62\x06proto3')



_USERID = DESCRIPTOR.message_types_by_name['userId']
_BOOKINGDATAGET = DESCRIPTOR.message_types_by_name['BookingDataGet']
_BOOKINGDATAPOST = DESCRIPTOR.message_types_by_name['BookingDataPost']
_DATES = DESCRIPTOR.message_types_by_name['dates']
_EMPTYBOOKING = DESCRIPTOR.message_types_by_name['EmptyBooking']
userId = _reflection.GeneratedProtocolMessageType('userId', (_message.Message,), {
  'DESCRIPTOR' : _USERID,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:userId)
  })
_sym_db.RegisterMessage(userId)

BookingDataGet = _reflection.GeneratedProtocolMessageType('BookingDataGet', (_message.Message,), {
  'DESCRIPTOR' : _BOOKINGDATAGET,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:BookingDataGet)
  })
_sym_db.RegisterMessage(BookingDataGet)

BookingDataPost = _reflection.GeneratedProtocolMessageType('BookingDataPost', (_message.Message,), {
  'DESCRIPTOR' : _BOOKINGDATAPOST,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:BookingDataPost)
  })
_sym_db.RegisterMessage(BookingDataPost)

dates = _reflection.GeneratedProtocolMessageType('dates', (_message.Message,), {
  'DESCRIPTOR' : _DATES,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:dates)
  })
_sym_db.RegisterMessage(dates)

EmptyBooking = _reflection.GeneratedProtocolMessageType('EmptyBooking', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYBOOKING,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:EmptyBooking)
  })
_sym_db.RegisterMessage(EmptyBooking)

_BOOKING = DESCRIPTOR.services_by_name['Booking']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERID._serialized_start=17
  _USERID._serialized_end=41
  _BOOKINGDATAGET._serialized_start=43
  _BOOKINGDATAGET._serialized_end=98
  _BOOKINGDATAPOST._serialized_start=100
  _BOOKINGDATAPOST._serialized_end=164
  _DATES._serialized_start=166
  _DATES._serialized_end=203
  _EMPTYBOOKING._serialized_start=205
  _EMPTYBOOKING._serialized_end=219
  _BOOKING._serialized_start=222
  _BOOKING._serialized_end=382
# @@protoc_insertion_point(module_scope)
